import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-between items-center p-4 bg-gray-100">
          <Link href="/">
            <h1 className="text-xl font-bold">Dashboard</h1>
          </Link>
          <nav>
            <ul className="flex space-x-4">
              <li>
                <Link href="/products" className="text-slate-500 font-bold hover:underline">
                  Product
                </Link>
              </li>
              <li>
                <Link href="/about" className="text-slate-500 font-bold hover:underline">
                  About
                </Link>
              </li>
              <li>
                <Link href="/contact" className="text-slate-500 font-bold hover:underline">
                  Contact
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <div className="container mx-auto p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
